### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by chmiiller** [hansemannn/ti.accountkit#1]
Hi Hans, do you have any plans to create an Android version? Seems to be super useful =]

**Comment by hansemannn** [comment]
Hey there! As my Android skills are not as advanced as my iOS-ones, I won't be able to support it soon. But please feel free to provide a PR and we can get it in! 🚀

**Comment by hansemannn** [comment]
Initial work for Android done here: https://github.com/hansemannn/ti.accountkit/tree/android-dev

Done:
- Project creation
- SDK inclusion
- Method definition

Todo:
- Implement methods (major task)

Feel free to help!

**Comment by AppWerft** [comment]
I will look into
You find here: https://github.com/AppWerft/ti.accountkit

**Comment by AppWerft** [comment]
Whats about logout()?

**Comment by hansemannn** [comment]
Exposed using `logout()`

**Comment by AppWerft** [comment]
OK, then I will change from logOut to logout.

**Comment by hansemannn** [comment]
Added note to [appwerft/ti.accountkit](https://github.com/AppWerft/Ti.AccountKit), closing.
